# Project information
site_name: REPO_NAME

nav:
  - Home: index.md

site_author: Deepanshu Kaushik
site_description: >-
  DESCRIPTION

# Repository
repo_name: 001DEEPANSHU/Template-MLFlow-Project
repo_url: https://github.com/001DEEPANSHU/Template-MLFlow-Project

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/001DEEPANSHU
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/deepanshu-kaushik-795567154/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/001DEEPANSHU"  target="_blank" rel="noopener">Deepanshu Kaushik</a>